collection_name: agent_chroma
persist_directory: chroma_db
k: 3
min_relevance_score: 0.5
data_path: data/knowledge
md5_hex_store: data/knowledge/.ingested.json
allowed_knowledge_file_type: [".txt",".pdf"]

chunk_size: 200
chunk_overlap: 20
separators: ["\n\n","\n","。","!","?","！","？","."," "]
